- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Copy expense configuration file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: App pre-requisites
  ansible.builtin.include_role:
    name: common  # the name of the role
    tasks_from: app_pre-req  # the task name inside the role

- name: Start Nginx server
  ansible.builtin.systemd_service:
    name: nginx
    enabled: true
    state: restarted