- name: Remove existing App Content
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: absent

- name: Create Application Directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: directory

- name: Download & Extract Application content
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: "{{ app_location }}"
    remote_src: true




#- name: Delete existing App content
#  ansible.builtin.file:
#    path: /usr/share/nginx/html
#    state: absent

#- name: Create App Directory
#  ansible.builtin.file:
#    path: /usr/share/nginx/html
#    state: directory

# Instead of using two tasks, ( 1 task to copy the zipped file to the target server in tmp directory,
# and  then 1 task to unzip the file from tmp directory to the desired location inside the target server)
# We should use unarchive module which does both at the same time.

#    - name: Download Application content
#      ansible.builtin.get_url:
#        url: https:://expense-artifacts.s3.amazonaws.com/frontend.zip
#        dest: /tmp/frontend.zip

#- name: Download & Extract Application content
#  ansible.builtin.unarchive:
#    src: https://expense-artifacts.s3.amazonaws.com/frontend.zip
#    dest: /usr/share/nginx/html
#    remote_src: yes